Update connector documentation
hyperledger/caliper pull request #1007
Opened 2020-09-19 08:32 UTC by aklenik

__Ongoing work.__ In the meantime you can start reading and criticizing the __first 2 sections__ of the `Writing Connectors` page.

Also contains minor fixes/updates in other parts.

Relates to #1006 
Closes #963 

Signed-off-by: Attila Klenik <a.klenik@gmail.com>

2020-09-22 16:25 UTC, nklincoln requested changes
two minor comments 👍

2020-09-22 17:34 UTC, aklenik commented on docs/vNext/Fabric_Configuration.md
> +> __Note:__ `sendRequests` also accepts an array of request settings. However, Fabric does not support submitting an atomic batch of transactions like Sawtooth, so there is no guarantee that the orde
It's just a typical example of tx batches that can declare dependencies between txs in the same batch. Just to clarify what we mean by independent txs for fabric. I can remove that part if it's confusing

2020-09-23 05:57 UTC, aklenik commented on docs/vNext/Fabric_Configuration.md
> +* `timeout`: _number. Optiona._ The timeout in seconds to use for this request.
Fixed.

2020-09-23 14:43 UTC, nklincoln commented on docs/vNext/Fabric_Configuration.md
> +> __Note:__ `sendRequests` also accepts an array of request settings. However, Fabric does not support submitting an atomic batch of transactions like Sawtooth, so there is no guarantee that the orde
i don't think it's an important change tbh

2020-09-23 15:37 UTC, nklincoln approved these changes

2020-09-23 16:10 UTC, merged