PeerGateway connector: Added new methods in the ConnectionProfileDefinition
hyperledger/caliper pull request #1253
Opened 2022-03-07 16:24 UTC by fraVlaca

Added changes to ConnectionProfileDefinition with test for new PeerGateway connetor.
The following methods were added:
- getPeersListForOrganization()
- getTlsCertForPeer(peer)
- getGrpcEndPointForPeer(peer)
- getGrpcOptionForPeer(peer)
Furthermore, connector-versions/peer-gateway was added to nyc of caliper-fabric.

2022-03-08 15:02 UTC, davidkel requested changes
For general coding a lot of the lines are like this
```
if (!this.connectionProfile.client){
```

The general pattern of the caliper code base is to have a space before the `{`, ie so it looks like
```
if (!this.connectionProfile.client) {
```

2022-03-08 15:02 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +        it('should through an error if no grpcOption property for the provided peer is found', async () => {
grpcOptions are optional

2022-03-08 16:40 UTC, fraVlaca commented on packages/caliper-fabric/lib/connector-configuration/ConnectionProfileDefinition.js
> +        if (!this.connectionProfile.peers){
should I really create a function for a one line check? would the function be a check to throw an error or just return true or false? if it is the second I did not really save any lines of code in the end...

2022-03-10 16:08 UTC, davidkel requested changes
Sorry, some more changes

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +        it('should return the parsed for a grpcs url', async () => {
this description is not quite right, but would suggest `should return the correct endpoint for a grpcs url`

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +        it('should return the parsed url for a grpc url', async () => {
We can change this description to be similar to above `should return the correct endpoint for a grpc url`

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +
can remove this blank line

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +        it('should return them when provided', async () => {
`should return the defined grpcOptions if present`

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +        it('should throw an error if no peers property is found', async () => {
`is found in the connection profile`

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +        it('should return an empty object if no grpcOption property for the provided peer was found', async () => {
grpcOption --> grpcOptions

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/lib/connector-configuration/ConnectionProfileDefinition.js
> +    getGrpcOptionForPeer(peer) {
method name should be `getGrpcOptionsForPeer` just missing the `s`

2022-03-10 16:08 UTC, davidkel commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +                `${peer} provided does not have url property provided in the connection Profile`            );
remove the extra blank spaces

2022-03-10 16:35 UTC, davidkel commented on packages/caliper-fabric/lib/connector-configuration/ConnectionProfileDefinition.js
> +            if (this.connectionProfile.organizations[org].mspid === mspid){
could we add a space before the `{` please

2022-03-11 09:29 UTC, fraVlaca commented on packages/caliper-fabric/test/connector-configuration/ConnectionProfileDefinition.js
> +        it('should throw an error if path provided through tlsCAcets.path does not point to a valid cert', async () => {
one is for the the .path property not pointing to a valid ceer while the other one is for a not valid cert in the .pem property. Should I revome anyway or is it sendible to have two different ones?

2022-03-11 16:50 UTC, davidkel approved these changes
LGTM

2022-03-11 16:50 UTC, merged