Fix #536 Update error messages for 'caliper-cli' package
hyperledger/caliper pull request #1348
Opened 2022-05-17 18:26 UTC by Tezas-6174

- [] Partially fixes #536 
- [] The error messages are clear and consistent.
- [] All the error messages are checked and updated.

2022-05-20 16:59 UTC, davidkel commented on packages/caliper-cli/caliper.js
> +    // console.log(results._[0]);
could you remove the commented out line

2022-05-20 16:59 UTC, davidkel requested changes
One minor comment from me

2022-05-20 23:05 UTC, Tezas-6174 commented on packages/caliper-cli/caliper.js
> +    // console.log(results._[0]);
Yes, removed it.

2022-05-23 10:58 UTC, davidkel commented
this change can't be merged until #1352 is merged

2022-05-27 10:02 UTC, davidkel approved these changes
LGTM

2022-05-27 10:02 UTC, merged