Port the publish workflow to GitHub Actions
hyperledger/caliper pull request #1384
Opened 2022-06-21 20:14 UTC by CaptainIRS

In this PR:
* The publish workflow is ported from Azure Pipelines to GitHub Actions as it is. Optimizations would be done in later PRs
* The publish action currently runs after unit and integration tests on committing to the main branch

Closes #1369

2022-06-21 20:42 UTC, davidkel requested changes
In the original azure implementation, when a PR is merged, only the unit tests were run before the publish step rather than the unit and integration tests so it's this we need to replicate for now.

I'm also thinking that to avoid conflict we need to remove the azure pipelines publish at the same time.

2022-06-22 09:48 UTC, davidkel requested changes
Looking good, just a couple of comments and to confirm that I understand the purpose of main.yml

2022-06-22 09:48 UTC, davidkel commented on .github/workflows/main.yml
> +  integration-tests:
If this is a PR merge then we don't need to run the integration tests. The original azure pipelines just runs unit-tests followed by a publish on a merge

2022-06-22 11:52 UTC, CaptainIRS commented on .github/workflows/main.yml
> +name: CI (main)
This action is for a push to main (which includes a PR merge). Should I change it to something like "CI (merge)"?

2022-06-22 12:19 UTC, davidkel commented on .github/workflows/main.yml
> +name: CI (main)
How about CI (Publish) as this is what the CI is going to do here ?

2022-06-22 16:58 UTC, davidkel approved these changes
LGTM

2022-06-22 16:58 UTC, merged