Removed unused dependencies
hyperledger/caliper pull request #1544
Opened 2024-04-20 07:26 UTC by psankhe28

## Checklist
 - [x]  A link to the issue/user story that the pull request relates to
 - [ ]  How to recreate the problem without the fix
 - [ ]  Design of the fix
 - [ ]  How to prove that the fix works
 - [ ]  Automated tests that prove the fix keeps on working
 - [ ]  Documentation - any JSDoc, website, or Stackoverflow answers?

## Issue/User story
#1365 

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Discord history](https://discord.com/channels/905194001349627914/941417677778473031)

## Design of the fix

## Validation of the fix

## Automated Tests

## What documentation has been provided for this pull request

2024-04-22 08:02 UTC, davidkel requested changes
As said previously you also need to update package-lock.json. You can't just remove it from package.json. Please make sure your code base is upto date before doing so as large changes have been made to package-lock.json recently

2024-04-22 10:06 UTC, psankhe28 commented
> As said previously you also need to update package-lock.json. You can't just remove it from package.json. Please make sure your code base is upto date before doing so as large changes have been made to package-lock.json recently

I have added the updated package-lock.json too.

2024-04-22 16:43 UTC, davidkel requested changes
@psankhe28 unfortunately it's not that simple as package-lock.json contains the complete dependency tree, so unless you really know what you are doing I would suggest you don't edit package-lock.json and regenerate the package-lock.json using the standard npm commands. Make sure you are using the latest node 18 which should give you npm 8.19.4 or later.

2024-04-27 14:33 UTC, psankhe28 commented
> @psankhe28 unfortunately it's not that simple as package-lock.json contains the complete dependency tree, so unless you really know what you are doing I would suggest you don't edit package-lock.json and regenerate the package-lock.json using the standard npm commands. Make sure you are using the latest node 18 which should give you npm 8.19.4 or later.

Node 18.18.0 would work or it should be strictly 18?

2024-04-27 18:23 UTC, davidkel commented
@psankhe28 The latest version I am using is node 18.20.2, Caliper packages state 18.19.0 or higher. So install the latest node 18 version available. Suggest you use `nvm` to manage your node installations (unless you are on windows but then I would advocate using wsl2 rather than native windows for caliper development). https://github.com/nvm-sh/nvm

2024-04-27 19:13 UTC, psankhe28 commented
> @psankhe28 The latest version I am using is node 18.20.2, Caliper packages state 18.19.0 or higher. So install the latest node 18 version available. Suggest you use `nvm` to manage your node installations (unless you are on windows but then I would advocate using wsl2 rather than native windows for caliper development). https://github.com/nvm-sh/nvm

I am using windows and nvm too. The node version I have downloaded is 18.18.0. Should I switch to wsl?

2024-04-27 21:47 UTC, davidkel commented
@psankhe28 So I see there is an nvm for windows. I've not used it but I would hope it works similar for the bash version of nvm. So it should allow to install a newer version of node 18 and be able to switch to it and make it the default as well. Just try `nvm install 18.20.2` if you want to install a specific version. There should be that version available for windows. But node 18.18 isn't going to work as npm will reject it as the package.json files declare a newer version. I don't think anyone has tried to use native windows to develop with caliper. I don't as my focus is fabric and running fabric on windows is an interesting excercise in itself. I use wsl2.

2024-04-28 07:36 UTC, psankhe28 commented
Node version: 18.20.2
Npm version: 10.5.0

2024-04-28 09:59 UTC, davidkel commented
Yep, looks good.

2024-04-29 11:35 UTC, davidkel approved these changes
Looks good to me, many thanks for the contribution

2024-04-29 11:35 UTC, merged